"""empty message

Revision ID: 01968408e13b
Revises: ebb51404c93c
Create Date: 2022-08-10 16:04:06.095530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01968408e13b'
down_revision = 'ebb51404c93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'artist_id')
    )
    op.create_table('venue_genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'venue_id')
    )
    op.drop_table('venue_genre_table')
    op.drop_table('artist_genre_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_genre_table',
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='artist_genre_table_artist_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], name='artist_genre_table_genre_id_fkey'),
    sa.PrimaryKeyConstraint('genre_id', 'artist_id', name='artist_genre_table_pkey')
    )
    op.create_table('venue_genre_table',
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], name='venue_genre_table_genre_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='venue_genre_table_venue_id_fkey'),
    sa.PrimaryKeyConstraint('genre_id', 'venue_id', name='venue_genre_table_pkey')
    )
    op.drop_table('venue_genre')
    op.drop_table('artist_genre')
    # ### end Alembic commands ###
